### ISSUE TITLE
console.php / Artisan::command

### ISSUE THREAD

**Issue by mikerockett** [cerbero90/command-validator#3]
Just bumped into this - just what I need!

Any chance this can be made to work inside an `Artisan::command` closure? If there is already a way, what is it? Would also be great if we could validate `ask()` input - not sure how that could be done, if at all possible...

Thanks 👍

**Comment by cerbero90** [comment]
Hey @mikerockett, glad this package helped you out :)

Currently it's not possible to validate Artisan closure commands because their purpose is to register a simple console command.

If you need to define validation rules and custom messages and attributes, I would suggest you to create a Command class instead.

About the other question, this package has been created to validate the input specified in Artisan commands signature on runtime. I was considering adding helper methods for prompting input but the number of parameters for each method would have been to big (e.g. `validateChoice()` would have 8 parameters) and this solution would not be more advantageous than simply using the Laravel validator itself.
